export const MATCH_LIST_REQUEST = 'MATCH_LIST_REQUEST';
export const MATCH_LIST_SUCCESS = 'MATCH_LIST_SUCCESS';
export const MATCH_LIST_FAIL = 'MATCH_LIST_FAIL';

export const MATCH_CREATE_REQUEST = 'MATCH_CREATE_REQUEST';
export const MATCH_CREATE_SUCCESS = 'MATCH_CREATE_SUCCESS';
export const MATCH_CREATE_FAIL = 'MATCH_CREATE_FAIL';

export const MATCH_UPDATE_REQUEST = 'MATCH_UPDATE_REQUEST';
export const MATCH_UPDATE_SUCCESS = 'MATCH_UPDATE_SUCCESS';
export const MATCH_UPDATE_FAIL = 'MATCH_UPDATE_FAIL';

export const MATCH_DELETE_REQUEST = 'MATCH_DELETE_REQUEST';
export const MATCH_DELETE_SUCCESS = 'MATCH_DELETE_SUCCESS';
export const MATCH_DELETE_FAIL = 'MATCH_DELETE_FAIL';